name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Aucune étape de build configurée"

      - name: Check deployment files
        run: |
          echo "Checking Symfony templates..."
          test -f app/templates/bundles/TwigBundle/Exception/error.html.twig
          ls -la app/templates/bundles/TwigBundle/Exception/

      - name: Sync files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./
          server-dir: /var/www/online-webs/job-candys.jobmakombela.fr/
          exclude: |
            **/.git*
            **/.idea/**
            **/node_modules/**
            **/*.map
            **/*:Zone.Identifier
            **/.env
            **/.env.*
          dry-run: false
          log-level: verbose

