name: Deploy Job Candys

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Vérification des fichiers importants
      - name: Check deployment files
        run: |
          echo "Checking Symfony templates..."

          test -f app/templates/bundles/TwigBundle/Exception/error.html.twig

          echo "Template found:"
          ls -la app/templates/bundles/TwigBundle/Exception/

      # 3. Déploiement vers le Raspberry Pi
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avz
          path: ./
          remote_path: /var/www/online-webs/job-candys.jobmakombela.fr/
          remote_host: ${{ secrets.FTP_HOST }}
          remote_user: ${{ secrets.FTP_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
          remote_port: 22

